name: Build macOS DMG

on:
  push:
    tags:
      - 'v*'  # 如 v1.0.0 时触发

permissions:
  contents: write  # ⬅️ 加上这句，授权创建 Release

jobs:
  build-dmg:
    runs-on: macos-15  # Apple Silicon

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'  # jpackage 需要 JDK 14+

      - name: Strip v prefix
        id: version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Locate artifact
        id: artifact
        run: |
          JAR=$(find target -name "*.jar" | grep -v "sources" | grep -v "javadoc" | head -n1)
          RELATIVE_PATH=${JAR#target/}   # 去掉开头的 target/，得到 jar/xxx.jar
          echo "jar=$RELATIVE_PATH" >> $GITHUB_OUTPUT

      - name: Confirm icon exists
        run: ls -l assets/icon.icns

      - name: Package .dmg with jpackage
        run: |
          mkdir -p out
          jpackage \
            --type dmg \
            --name DesApp \
            --input target \
            --main-jar ${{ steps.artifact.outputs.jar }} \
            --main-class com.logan.DesApp \
            --icon assets/icon.icns \
            --java-options "-Xmx512m" \
            --dest out \
            --app-version "${{ steps.version.outputs.version }}" \
            --mac-package-identifier com.logan.desapp

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: DesApp-dmg
          path: out/DesApp-*.dmg

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: out/DesApp-*.dmg
          body: |
            ⚠️ **首次运行前请执行以下命令, 解除 macOS 限制：**

            ```bash
            xattr -d com.apple.quarantine ~/Applications/DesApp.app
            ```

            否则系统可能会提示「应用已损坏，无法打开」。
